spring.application.name=FirstProjectCadastro
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:Usuario
spring.datasource.driver-Class-Name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8081
spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.port=587
spring.mail.username=arthurwillyan0404fcl@gmail.com
spring.mail.password=zyry itqy lrwn buch
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
